sonar.projectKey=flask-devops-app
sonar.projectName=Flask DevOps App
sonar.projectVersion=1.0

sonar.sources=app
sonar.tests=app
sonar.test.inclusions=app/test_app.py
sonar.exclusions=**/test_*.py

sonar.python.version=3.11

sonar.python.coverage.reportPaths=coverage.xml
