apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: flask-app-rules
  namespace: monitoring
spec:
  groups:
  - name: flask-app
    rules:
    - alert: FlaskAppDown
      expr: kube_deployment_status_replicas_available{deployment="flask-app"} == 0
      for: 2m
      labels:
        severity: critical
      annotations:
        summary: "Flask app is DOWN"
        description: "Flask app has had 0 available replicas for 2 minutes."
---
apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: flask-app-alerts
  namespace: monitoring
spec:
  route:
    receiver: 'log-receiver'
    groupWait: 30s
    groupInterval: 5m
    repeatInterval: 1h
    matchers:
    - name: alertname
      value: FlaskAppDown
      matchType: "="
  receivers:
  - name: 'log-receiver'
    webhookConfigs:
    - url: 'http://localhost:5001/alerts'
      sendResolved: true